### ISSUE TITLE
evil mode

### ISSUE THREAD

**Issue by AlexFransis** [DogLooksGood/parinfer-mode#10]
Hi it seems when I am in insert mode I can't type "<" or ">" signs. Is there a quick fix for this? Otherwise it works very well with evil mode. Thanks

**Comment by DogLooksGood** [comment]
Hi, I'll address it and have a fix.
Thanks for reporting this problem.

**Comment by DogLooksGood** [comment]
Hi, @AlexFransis , Sorry for reply so late.
I'm failed on reproduce the problem, could you share your emacs configuration and the steps that will reproduce the problem?

**Comment by AlexFransis** [comment]
Hello, @DogLooksGood 
I am using spacemacs. This is what I have in my packages.el

```
(defun clojure/init-parinfer ()
  (use-package parinfer
    :ensure t
    :init
    (progn
      (add-hook 'clojure-mode-hook #'parinfer-mode)
      (add-hook 'emacs-lisp-mode-hook #'parinfer-mode))))
```

Thanks again

**Comment by DogLooksGood** [comment]
Hi, @AlexFransis, still unable to reproduce the problem, no matter `vim`, `emacs` or `hybrid`.

If you'd like to help me for this problem:
When the problem occurs, press `C-h k <` to see which command is bound to it.

The command for "<" should be `self-insert-command`. 

If it's not, for lately version `parinfer-mode` on MELPA(not MELPA stable), you can use following to have a quick fix.
```
;; add this to :init
(parinfer-strategy-add ‘default that-command)
```

If it is `self-insert-command`, I need your all configuration and the version of Emacs to reproduce the problem. 

Very appreciate for your help!

**Comment by AlexFransis** [comment]
Hello, @DogLooksGood ``C-h k <`` tells me that it is bound to command ``parinfer-shift-left``
For now i just commented out the keybinding for "<" and ">" so now I am able to use parinfer without problems.

Thanks again for you help!

**Comment by DogLooksGood** [comment]
@AlexFransis `parinfer-shift-left` or `parinfer-shift-right` should be used in `parinfer-region-mode`. this mode will be toggle on whenever you activate region, and toggle off whenever you deactivate region. Maybe you have manually toggle on this minor mode? 
 
BTW, Since these keybindings are not necessary, I'll remove them in next version.

**Comment by AlexFransis** [comment]
@DogLooksGood It seems that when I enter Insert mode, it toggles ``parinfer-region-mode`` because ``C-h k TAB`` is also mapped to command ``parinfer-shift-right``.

Maybe adjust ``parinfer-region-mode`` to not toggle when in Insert mode? It works very well when in Visual mode.

**Comment by DogLooksGood** [comment]
@AlexFransis 
```
(add-hook 'activate-mark-hook 'parinfer--regin-mode-enable t t)
```
and 
```
(remove-hook 'deactivate-mark-hook 'parinfer--region-mode-disable t)
```
For quick fix, you can comment these lines.
The `activate-mark-hook` means you're selecting region(I think, maybe I'm wrong), it should not be triggered when entering Insert mode.

**Comment by DogLooksGood** [comment]
close for now.
