### ISSUE TITLE
Press Tab/Shift-Tab to move cursor to next possible indentation.

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/parinfer-mode#14]
We need:
1. Calculate indentations those will affect code struct.
2. Highlight these indentations.
3. Let cursor move between these indentations.

**Comment by DogLooksGood** [comment]
Added as a new extension `smart-tab`.

**Comment by Engelberg** [comment]
I installed Parinfer using the require-package instructions:

```
(use-package parinfer
  :ensure t
  :bind
  (("C-," . parinfer-toggle-mode))
  :init
  (progn
    (setq parinfer-extensions
          '(defaults       ; should be included.
            pretty-parens  ; different paren styles for different modes.
            smart-tab      ; C-b & C-f jump positions and smart shift with tab & S-tab.
            smart-yank))   ; Yank behavior depend on mode.
    (add-hook 'clojure-mode-hook #'parinfer-mode)
    (add-hook 'emacs-lisp-mode-hook #'parinfer-mode)))
```

But I am not seeing any evidence of smart-tab behavior.  Tab still moves text to the one indentation point expected from the previous line, and Shift-Tab is not bound to anything.

Also, I would appreciate it if you could explain how parinfer is supposed to interact with cut-and-paste.  I'm seeing some behaviors with cut-and-paste and with commands like comment-out-region that seem to do weird things to the parens; I'd love to know what the intended behavior is .

**Comment by Engelberg** [comment]
Hmmm, it seems like it does work as long as a region is selected, just not when you want to mess around with a single line by hitting tab and shift-tab where the cursor is on the relevant line.

In CUA mode, weird things happen after you select a region and use tab and shift-tab.  Next time you hit tab, it seemingly randomly selects some region of text in the vicinity of the cursor.

**Comment by DogLooksGood** [comment]
Hi @Engelberg , there's 4 commands available:
- `parinfer-smart-tab:shift-right` (bound to tab) .
- `parinfer-smart-tab:shift-left`(bound to shift-tab).
- `parinfer-smart-tab:dwim-right` (no default keybinding).
- `parinfer-smart-tab:dwim-left` (no default keybinding).

`shift-right` and `shift-left` only available when region is active.
I guess you are looking for `dwim-right` and `dwim-left`. 
you can replace the :bind section with this:
```
:bind
(:map parinfer-mode-map
      ("<tab>" . parinfer-smart-tab:dwim-right)
      ("S-<tab>" . parinfer-smart-tab:dwim-right)
      ("C-," . parinfer-toggle-mode)
 :map parinfer-region-mode-map
      ("<tab>" . parinfer-smart-tab:dwim-right)
      ("S-<tab>" . parinfer-smart-tab:dwim-right))
```
`dwim` version has three behavior:
1. when region is active, behave as same as `shift`.
2. when your cursor is locate at an empty line, it will find next meaningful position. 
3. otherwise, it will move current line to next indentation. (instead of fix indentation)

Sorry for my poor English, but I wish I can eliminate your confusion. 

BTW, i've no experience with CUA mode, I'll have a try on CUA-mode to see what i can do for compatibility.

**Comment by DogLooksGood** [comment]
When you paste something that have unbalanced parens, `parinfer-mode` will fix parens.

If you paste in `Indent Mode`, the indentation be preserved. So according to the rule of Parinfer, the parens may change after pasting.

e.g., paste `(foo )))` at cursor`|`
```
(defun hello ())
  |
```
=>
```
(defun hello ()
  (foo))   ;; <-- auto add ) here
```

If you paste in `Paren Mode`, the parens around will not be changed, but the indentation will be fix.
e.g. paste `(foo )))` at cursor `|`.
```
(defun hello ()
|
  (baz)) 
```
=>
```
(defun hello ()
  (foo)   ;; <-- auto indent this line
  (baz))
```

**Comment by Engelberg** [comment]
Thanks, it's mostly working the way I want now.

The main problem I'm still having is that when I select a region and use this dwim-right tab on it, when I'm in CUA mode, the Ctrl-g command isn't working me to exit region mode, so the parens aren't recomputed.  Is there another way to exit region mode?

**Comment by Engelberg** [comment]
As part of CUA mode, I'm using transient-mark-mode.

**Comment by DogLooksGood** [comment]
I've already see this issues, `C-g` is bound to cua-cancel, I think I can fix this problem by adding an extension.

**Comment by Engelberg** [comment]
I have a key bound to comment-or-uncomment-region, and this is another instance where parinfer doesn't kick in right away and rebalance parens until I start to do other editing.

**Comment by DogLooksGood** [comment]
@Engelberg 
For quick fix, you can use `parinfer-strategy-add` 
```
(parinfer-strategy-add 'instantly '(cua-cancel comment-or-uncomment-region))
```

**Comment by DogLooksGood** [comment]
Sorry, the quick fix won't work. please wait for fix. :(

**Comment by DogLooksGood** [comment]
@Engelberg Should be fixed in v0.4.1 on melpa stable. Or newer melpa version.

**Comment by Engelberg** [comment]
Thanks!

**Comment by markx** [comment]
IMHO, when you use the indent mode, you always need to manage all the indentation manually, like you will often need to increase/decrease the indentation for a line, and in this case, the `TAB` key's default function (automatically indenting the line) is not very useful, if at all. Would it make more sense to use `TAB` and `S-TAB` instead of `C-f` and `C-b` to move the cursor?

**Comment by DogLooksGood** [comment]
Hey, @markx
You can configure like this:
```emacs-lisp
;; use dwim-right-or-complete if you use company and used to manually trigger completion with tab, dwim-right-or-complete
;; will complete when cursor is after a word,
;; will shift region when region is active,
;; will move cursor to next indentation when line is empty,
;; otherwise, shift current line.
(bind-key "<tab>" 'parinfer-smart-tab:dwim-right-or-complete parinfer-mode-map)

;; dwim-right, if you don't need to manaually trigger completion with tab.
(bind-key "<tab>" 'parinfer-smart-tab:dwim-right-or-complete parinfer-mode-map)

(bind-key "S-<tab>" 'parinfer-smart-tab:dwim-left parinfer-mode-map)

;; following configuration should be add to :config of use-package
(parinfer-strategy-add 'instantly
  '(parinfer-smart-tab:dwim-right     
    parinfer-smart-tab:dwim-right-or-complete
    parinfer-smart-tab:dwim-left))
```
is this help?

**Comment by markx** [comment]
@DogLooksGood Yeah this is exactly what I like, and I was just suggesting making this the default.

**Comment by DogLooksGood** [comment]
@markx Thx for suggestion!
To making the default, we have to make sure this command works out of box in all the situations. However,  emacsers' `TAB` key are highly customized. For example, there're `yasnippet` users and  `auto-complete` users. 

I have plan to make it the default or easier to configure this, but I'm still not clear about how to do this.
