### ISSUE TITLE
Use with Evil.

### ISSUE THREAD

**Issue by DogLooksGood** [DogLooksGood/parinfer-mode#3]
The parinfer-indent or parinfer-paren should be called after very command in evil normal state and evil visual state.

**Comment by jiegec** [comment]
Potential candidates:
```
evil-{normal,visual}-state-{entry,exit}-hook
```

**Comment by DogLooksGood** [comment]
I think using both both `parinfer-mode` and `evil-state` may be too complex.
Need to find a good combination.

**Comment by DogLooksGood** [comment]
I think using evil-cleverparens will be a good idea, just like nvim-parinferjs + vim-sexp. Actuallly have Paren Mode + Indent Mode in evil-normal-state is too verbose.
