### ISSUE TITLE
Install by package from melpa: Symbol's function definition is void: font-lock-flush

### ISSUE THREAD

**Issue by zhcosin** [DogLooksGood/parinfer-mode#30]
The error has occur when I install parinfer from melpa by packages manager, The *message* buffer show the following message: 
parinfer-ext::pretty-parens:paren: Symbol's function definition is void: font-lock-flush
And my Emacs is 25.

**Comment by DogLooksGood** [comment]
For quick fix:
```
(defun font-lock-flush ()
  (when font-lock-mode
    (with-no-warnings
      (font-lock-fontify-buffer))))
```

This will be fixed in the next version.
Leave this open until the bug is fixed.

**Comment by DogLooksGood** [comment]
@zhcosin this bug is fixed, please check.
