### ISSUE TITLE
defn with docstring results in strange indent

### ISSUE THREAD

**Issue by Engelberg** [DogLooksGood/parinfer-mode#40]
In parinfer indent mode when I type:

```
(defn f "doc-string"
``` 

and then hit enter, the defn line indents and becomes part of the body of the previous function.

**Comment by DogLooksGood** [comment]
It's seems this is not a bug of parinfer.
I can reproduce even though I disabled parinfer-mode.

**Comment by Engelberg** [comment]
Weird, what other aspect of emacs or clojure-mode could automatically trigger an indent upon hitting the enter key?

**Comment by DogLooksGood** [comment]
not sure, maybe clojure-mode.

**Comment by DogLooksGood** [comment]
Hi, @Engelberg . This is the behavior of `electric-indent-mode`. 

Here's a solution for this.
## 1.disable electric-indent-mode. 
```emacs-lisp
(electric-indent-mode -1)
```

## 2.remap newline to newline-and-indent.
Without electric-indent-mode, the newline command won't provide any indentation. So we have to use newline-and-indent command.

## 3.let parinfer handle command newline-and-indent.
add following to `:config` section of `(use-package parinfer ...)`
```emacs-lisp
(parinfer-strategy-add 'default 'newline-and-indent)
```


BTW, I don't think inline doc string with the function name is the common usage. I'll have a fix on letting Parinfer handle `newline-and-indent` by default, but won't let Parinfer auto disable `electric-indent-mode`.
