### ISSUE TITLE
save-mark-and-excursion is undefined in the prior version of Emacs

### ISSUE THREAD

**Issue by zhcosin** [DogLooksGood/parinfer-mode#43]
Hi, I found a problem about parinfer-mode but it maybe is not problem of parinfer-mode.
The cursor will auto backward many lines when I use backspace delete char in evil insert state, and the problem went away when I disable parinfer-mode.
The problem only found in Emacs 24.5 on windows 7, not be found in Emacs 24 on debian.

**Comment by DogLooksGood** [comment]
Hi, @zhcosin , Which function is bound to the backspace delete char when the issue occur?
You can query it via `C-h k`.

BTW, Is that you have the same configuration for your Emacs on Window7 and Emacs on Debian?

**Comment by zhcosin** [comment]
The configuration is same, and the function bind to <backspace> is parinfer-backward-delete-char.

**Comment by zhcosin** [comment]
I use emacs 25.1 and re-install all packages so the problem is went away.

**Comment by DogLooksGood** [comment]
I just have a fix for this.
88fc370113c124eeebc687f26a8c43d4564e5486
