### ISSUE TITLE
Can't enable paredit extension

### ISSUE THREAD

**Issue by Mihara** [DogLooksGood/parinfer-mode#45]
```
File mode specification error: (invalid-function bind-key)
parinfer-paredit:init: Invalid function: bind-key
```
Installing the bind-key package does not fix the situation, so I'm not quite sure what exactly is broken.

**Comment by DogLooksGood** [comment]
`bind-key` is a function from `use-package`. but since parinfer doesn't declare the dependency of `use-package`. `bind-key` should not be used.

I'll have a fix.

**Comment by DogLooksGood** [comment]
use-package has been changed to define-key, f3ab1b6a47d7c05effa260ae2f6b3bd35edf078a.
