### ISSUE TITLE
parinfer--prepare: Invalid function: parinfer-save-excursion

### ISSUE THREAD

**Issue by marcinwaldowski** [DogLooksGood/parinfer-mode#46]
After installing parinfer 0.4.10 from MELPA Stable in emacs 24.5 I cannot work on clojure files anymore. Cursor jumps to random place on backspace and in *Messages* I see lines:
`parinfer--prepare: Invalid function: parinfer-save-excursion`.

It looks like version 0.4.9 works correctly. Previously I used version 0.4.5 which also worked for me.

**Comment by DogLooksGood** [comment]
This is not related to the changes in 0.4.10 I think. the function `parinfer-save-excursion` should be an alias to `save-excursion`.  I need some help.

Please execute  `(defalias 'parinfer-save-excursion 'save-excursion)` manually,
you can do this with `M-:`, enter the form then press enter.

Then, will this problem still occurred?

**Comment by marcinwaldowski** [comment]
Thanks for the answer.

Executing `(defalias 'parinfer-save-excursion 'save-excursion)` doesn't help. The problem still occurs.

`C-h k backspace` doesn't show anything. I tried `C-h c backspace` and it prints:
`DEL (translated from <backspace>) runs the command backward-delete-char-untabify`.

Previously I wrote *jumps to random place*. I should have wrote *jumps to beggining of buffer*. Also sometimes it behave same way for enter.

`C-h c backspace` result with:
`RET (translated from <return>) runs the command newline`

**Comment by marcinwaldowski** [comment]
I removed all .elc files from `.emacs.d/elpa/parinfer-0.4.10`, restarted emacs and now version 0.4.10 works for me. It looks like there is a need to now Emacs internals to actually use it. Sorry for bothering and big thanks for great Parinfer for Emacs.
