### ISSUE TITLE
Wrapping parens doesn't work

### ISSUE THREAD

**Issue by f4k3-pixel** [DogLooksGood/parinfer-mode#73]
I don't have any fancy config. I just configured parinfer-mode as suggested, i.e. it is a very default setup →

```emacs-lisp
  (use-package parinfer
    :bind (("C-," . parinfer-toggle-mode))
    :defer t
    :hook ((lisp-mode       . parinfer-mode)
           (clojure-mode    . parinfer-mode)
           (emacs-lisp-mode . parinfer-mode)
           (scheme-mode     . parinfer-mode))
    :init (setq parinfer-extensions '(defaults pretty-parens evil)
                  parinfer-auto-switch-indent-mode t))
```

But inserting a '(' before another doesn't work as suggested over [here](https://shaunlebron.github.io/parinfer/#inserting-parens) →

Expected:
```lisp
(foo [1 2 3 4 5 6])
```
Actual:
```lisp
(foo []1 2 3 4 5 6)
```
Trying to insert before 1 causes this behavior.

**Comment by andreyorst** [comment]
This works for me as intended. Are you sure you don't have any other modes for inserting parens enabled alongside parinfer?

**Comment by f4k3-pixel** [comment]
Thanks! electric-pair-mode was interfering with parinfer. It works as expected now :D
