### ISSUE TITLE
Availability through package-install

### ISSUE THREAD

**Issue by AlexAti** [DogLooksGood/parinfer-mode#8]
Hello,

I think it would be useful to have this great project available to emacs through MELPA or Marmalade.

I was very surprised (and dissapointed) when I saw I can't yet install parinfer in emacs through package.el, while most other modern editors have had parinfer available in their plugin repositories since months ago.

If you could add your project to any of the community emacs packages repositories, I think you would do the emacs project a big favor!

Thanks for sharing your work!

**Comment by DogLooksGood** [comment]
Hi, @AlexAti 
This should be ready for installation with MELPA
https://melpa.org/#/parinfer
or MELPA Stable
https://stable.melpa.org/#/parinfer

But since it was been deployed very recently, maybe you can try `M-x package-refresh-contents`?

**Comment by AlexAti** [comment]
Did it, and worked perfectly. Thanks again!
